
image: registry.gitlab.com/pages/hugo:latest

script: docker login -u $CI_JOB_USER -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
