name: S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/s3 -v ${{ github.workspace }}/_site:/srv/s3/_site \
        s3/builder:latest /bin/bash -c "chmod -R 777 /srv/s3 && s3 build --future"
